@all:
	d2 software-analysis-tools.d2 software-analysis-tools.png
	d2 the-tedious-detail-1.d2 the-tedious-detail-1.png
	d2 the-tedious-detail-2.d2 the-tedious-detail-2.png
	d2 naive-solution.d2 naive-solution.png
	d2 techniques.d2 techniques.png
	d2 stack-graph-example.d2 stack-graph-example.png
	d2 dependency-graph-example.d2 dependency-graph-example.png
	d2 reference-resolution-algorithm.d2 reference-resolution-algorithm.png
