literature: "Literature"
byhand: "Code transformation"
ast: "AST translation"
famix: "Meta-modelling"
lf: "Language Frontends"

literature -- byhand
literature -- ast
literature -- famix
literature -- lf
