direction: down
classes: {
  server: {
    shape: image
    icon: ../icons/server.svg
  }
  c: {
    shape: image
    icon: ../icons/c.svg
  }
  csharp: {
    shape: image
    icon: ../icons/csharp.svg
  }
  cpp: {
    shape: image
    icon: ../icons/cpp.svg
  }
  python: {
    shape: image
    icon: ../icons/python.svg
  }
  java: {
    shape: image
    icon: ../icons/java.svg
  }
  rust: {
    shape: image
    icon: ../icons/rust.svg
  }
  js: {
    shape: image
    icon: ../icons/js.svg
  }
  ruby: {
    shape: image
    icon: ../icons/ruby.svg
  }
  go: {
    shape: image
    icon: ../icons/go.svg
  }
  lua: {
    shape: image
    icon: ../icons/lua.svg
  }
  fortran: {
    shape: image
    icon: ../icons/fortran.svg
  }
  asm: {
    shape: image
    icon: ../icons/asm.svg
  }
}

tool: "Analysis tool" {class: server}

project_A: "Project A" {
  component_python: "" {class: python}
  component_c: "" {class: c}
  component_python <> component_c
}

project_B: "Project B" {
  component_java: "" {class: java}
  component_cpp: "" {class: cpp}
  component_java <> component_cpp
}

project_C: "Project C" {
  component_cpp: "" {class: cpp}
  component_fortran: "" {class: fortran}
  component_cpp <> component_fortran
}

project_D: "Project D" {
  component_go: "" {class: go}
  component_asm: "" {class: asm}
  component_go <> component_asm
}

project_E: "Project E" {
  component_lua: "" {class: lua}
  component_csharp: "" {class: csharp}
  component_lua <> component_csharp
}

tool -> project_A
tool -> project_B
tool -> project_C
tool -> project_D
tool -> project_E
